# Generated by Django 4.1.3 on 2025-09-19 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameworkControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('control_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('element_type', models.CharField(blank=True, default='', max_length=50)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='framework_controls', to='risk.framework')),
            ],
            options={
                'ordering': ['framework', 'control_id'],
                'unique_together': {('framework', 'control_id')},
            },
        ),
        migrations.AddField(
            model_name='control',
            name='framework_controls',
            field=models.ManyToManyField(blank=True, related_name='controls', to='risk.frameworkcontrol'),
        ),
    ]
